name: Unzip issue test in GitHub hosted

on:
  # push:
  #   branches:
  #     - unzip-issue
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: priyagupta108/setup-python@fix-windows-extract-archive
      with:
        # python-version: ${{ matrix.python-version }}
        python-version: |
            3.8
            3.9
            pypy3.9-nightly
            pypy3.8
            3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
